server:
  port: 8082
spring:
  thymeleaf:
    cache: false
    mode: HTML
  dubbo:
    appname: consumer
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20881
    consumer:
      check: false
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application


threadpool:
  core-pool-size: 5
  max-pool-size: 5
  queue-capacity: 1000
  keep-alive-seconds: 300