
server:
  port: 8848
spring:
  dubbo:
    appname: provider
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20880
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/1904a?useUnicode=true&characterEncoding=UTF-8
    # druid 数据源
    #redis连接池信息
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 20000
    database: 0
    #配置哨兵集群
    sentinel:
      master: mymaster
      nodes: 192.168.154.128:26379,192.168.154.128:26380,192.168.154.128:26381
    cluster:
      #配置redis集群
      nodes: 192.168.154.128:6379,192.168.154.128:6380,192.168.154.128:6381


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jk.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
